"""Filesystem watcher (v0.12.0).

Background service that watches every enabled library root with the
``watchdog`` library and triggers the scan → match → build pipeline when
new media lands on disk. Designed to be reliable in the face of partial
imports (Sonarr/Radarr copying multi-gigabyte files) and noisy file events
generated by metadata-aware downloaders.

Design notes
------------
* **Triggers**: directory creation/move events under any library root, plus
  new media-file appearances inside an already-tracked show folder. Both
  collapse to the same debounce key (the immediate child of the library
  root, i.e. the show or movie folder).
* **Debounce**: a configurable per-folder timer (default 30s, env var
  ``WATCHER_DEBOUNCE_SECONDS``, user-overridable from Settings → Watcher).
  Every fresh event for the same folder resets the timer so a 30-minute
  multi-file copy is treated as a single "show settled" event.
* **Stability check**: right before dispatch, the watcher snapshots the
  recursive size+mtime of the folder and waits one short interval to
  confirm nothing changed. If files are still being written, the timer
  is rescheduled instead of firing.
* **Pipeline**: ``scan_library`` → ``auto_match_*`` (respecting per-library
  metadata source) → ``build_svc.start_build``. If the match fails or
  scores below the user's ``auto_match_threshold``, the folder is queued
  in ``watcher_review`` (db) instead of silently skipped.
* **Activity**: every state transition is appended to an in-memory ring
  buffer surfaced at ``GET /api/watcher/events`` so the dedicated
  Watcher page can render a live timeline.
* **Hot reload**: ``reload()`` re-reads the active settings and the
  current library set, then re-arms watches accordingly. Called by the
  settings + library routes so toggling the watcher or enabling a new
  library takes effect immediately, no restart needed.
"""
from __future__ import annotations

import asyncio
import os
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from loguru import logger

try:
    from watchdog.events import (
        DirCreatedEvent,
        DirMovedEvent,
        FileCreatedEvent,
        FileMovedEvent,
        FileSystemEvent,
        FileSystemEventHandler,
    )
    from watchdog.observers import Observer
    _WATCHDOG_AVAILABLE = True
except Exception as e:  # pragma: no cover - import guard only
    logger.warning("watchdog import failed; filesystem watcher disabled: {}", e)
    Observer = None  # type: ignore[assignment]
    FileSystemEventHandler = object  # type: ignore[assignment]
    _WATCHDOG_AVAILABLE = False

from .. import db
from ..config import (
    MEDIA_ROOT,
    effective_metadata_source,
    effective_watcher_debounce_seconds,
    effective_watcher_enabled,
    get_user_settings,
)
from . import builder as build_svc
from . import matcher as matcher_svc
from . import scanner as scanner_svc
from . import sidecar as sidecar_svc
from .parser import is_video


# Files we should never react to even if they trigger a create event.
# These are sidecars the builder/scanner produces or transfer leftovers.
_IGNORED_SUFFIXES = {
    ".nfo",
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".tbn",
    ".part",
    ".partial",
    ".tmp",
    ".!qb",
    ".crdownload",
    ".filepart",
    ".pyc",
}
_IGNORED_NAME_PREFIXES = ("._", ".",)

# Max events kept in the in-memory ring buffer.
_EVENT_BUFFER_SIZE = 500

# After the debounce timer fires, run one short stability poll to make sure
# the folder hasn't grown since the timer was scheduled. This catches the
# edge case where a downloader pauses ~debounce_seconds mid-copy.
_STABILITY_POLL_INTERVAL = 5  # seconds
_STABILITY_POLL_MAX = 3        # iterations


@dataclass
class WatcherEvent:
    """One row in the in-memory activity ring buffer."""

    timestamp: int
    event_type: str          # detected | debounced | processing | matched | built | queued_for_review | error
    folder_path: str
    library: Optional[str]
    message: str
    status: str = "info"     # info | success | warning | error

    def as_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "folder_path": self.folder_path,
            "library": self.library,
            "message": self.message,
            "status": self.status,
        }


@dataclass
class _PendingFolder:
    """Per-folder debounce state."""

    library: str
    timer: Optional[asyncio.TimerHandle] = None
    last_event_at: float = field(default_factory=time.monotonic)


class _LibraryEventHandler(FileSystemEventHandler):
    """watchdog → asyncio bridge for a single library root.

    All filesystem events arrive on watchdog's internal thread; we trampoline
    interesting ones back to the watcher's event loop via
    ``loop.call_soon_threadsafe`` so the rest of the pipeline can run as
    normal coroutines.
    """

    def __init__(self, *, watcher: "Watcher", library: str, library_root: Path) -> None:
        self._watcher = watcher
        self._library = library
        self._library_root = library_root.resolve()

    # watchdog fires create/move events for both files and directories. We
    # listen to both and let _on_event filter to the cases we actually care
    # about — folder creation + new video file appearance.

    def on_created(self, event: FileSystemEvent) -> None:  # noqa: D401
        self._dispatch(event, getattr(event, "src_path", ""))

    def on_moved(self, event: FileSystemEvent) -> None:  # noqa: D401
        # On move we care about the destination, since that's where the new
        # content has landed.
        dest = getattr(event, "dest_path", None) or getattr(event, "src_path", "")
        self._dispatch(event, dest)

    def _dispatch(self, event: FileSystemEvent, raw_path: str) -> None:
        try:
            if not raw_path:
                return
            p = Path(raw_path)
            # Skip hidden / temp files outright before any path resolution.
            name = p.name
            if not name:
                return
            if any(name.startswith(pref) for pref in _IGNORED_NAME_PREFIXES):
                return
            suffix = p.suffix.lower()
            if suffix in _IGNORED_SUFFIXES:
                return
            is_dir = bool(getattr(event, "is_directory", False))
            # For file events, only react to media file appearances. NFO,
            # artwork, and transfer leftovers were filtered above; this is
            # the final guard.
            if not is_dir and not is_video(p):
                return
            # Resolve the "show folder" — the immediate child of the library
            # root that this event belongs to. Top-level library events
            # (someone created a brand-new library) are ignored; library
            # detection is a separate explicit user action.
            try:
                rel = p.resolve().relative_to(self._library_root)
            except (ValueError, OSError):
                return
            parts = rel.parts
            if not parts:
                return
            show_folder = self._library_root / parts[0]
            # Hand off to the asyncio loop.
            self._watcher._notify_event(self._library, show_folder, raw_path, is_dir)
        except Exception as e:  # pragma: no cover - defensive
            logger.warning("watcher dispatch error: {}", e)


class Watcher:
    """Owns the watchdog Observer and per-folder debounce state."""

    def __init__(self) -> None:
        self._observer: Optional[Any] = None
        self._loop: Optional[asyncio.AbstractEventLoop] = None
        self._pending: dict[Path, _PendingFolder] = {}
        self._running: dict[Path, asyncio.Task] = {}
        self._events: deque[WatcherEvent] = deque(maxlen=_EVENT_BUFFER_SIZE)
        self._events_lock = threading.Lock()
        self._watched_paths: list[str] = []
        self._enabled = False
        # Protect against concurrent start/stop/reload calls.
        self._lifecycle_lock = threading.Lock()

    # ----- lifecycle ------------------------------------------------------

    def start(self, loop: Optional[asyncio.AbstractEventLoop] = None) -> None:
        """Start the watcher on the given (or current) event loop.

        Idempotent: a second call after a successful start is a no-op. Will
        skip starting entirely when the watcher is disabled in settings or
        when ``watchdog`` failed to import.
        """
        with self._lifecycle_lock:
            if not _WATCHDOG_AVAILABLE:
                logger.warning("watchdog not available; watcher will not start")
                return
            if self._observer is not None:
                return
            if not effective_watcher_enabled():
                logger.info("Filesystem watcher is disabled via settings; not starting")
                self._enabled = False
                return
            try:
                self._loop = loop or asyncio.get_running_loop()
            except RuntimeError:
                logger.warning("No running event loop; watcher cannot start")
                return
            self._build_observer()
            self._enabled = True
            self._record_event(
                event_type="started",
                folder_path="",
                library=None,
                message=(
                    f"Watcher started on {len(self._watched_paths)} library "
                    f"path(s); debounce={effective_watcher_debounce_seconds()}s"
                ),
                status="success",
            )

    def stop(self) -> None:
        """Stop the observer and cancel any pending debounce timers."""
        with self._lifecycle_lock:
            self._teardown_observer()
            self._enabled = False
            self._record_event(
                event_type="stopped",
                folder_path="",
                library=None,
                message="Watcher stopped",
                status="info",
            )

    def reload(self) -> None:
        """Re-evaluate settings and re-arm watches.

        Called by the settings + library routes whenever something changed
        that affects what should be watched. Safe to call from any thread —
        the actual observer manipulation is serialised by the lifecycle lock.
        """
        with self._lifecycle_lock:
            enabled = effective_watcher_enabled() and _WATCHDOG_AVAILABLE
            if not enabled:
                if self._observer is not None:
                    self._teardown_observer()
                    self._enabled = False
                    self._record_event(
                        event_type="stopped",
                        folder_path="",
                        library=None,
                        message="Watcher disabled via settings",
                        status="info",
                    )
                return
            # Enabled: tear down and rebuild so newly-enabled libraries pick
            # up watches and disabled libraries are dropped.
            if self._observer is not None:
                self._teardown_observer()
            try:
                self._loop = self._loop or asyncio.get_running_loop()
            except RuntimeError:
                logger.warning("No running event loop during reload; deferring")
                return
            self._build_observer()
            self._enabled = True
            self._record_event(
                event_type="reloaded",
                folder_path="",
                library=None,
                message=(
                    f"Watcher reloaded; watching {len(self._watched_paths)} "
                    f"path(s), debounce={effective_watcher_debounce_seconds()}s"
                ),
                status="info",
            )

    # ----- introspection --------------------------------------------------

    def status(self) -> dict[str, Any]:
        return {
            "available": _WATCHDOG_AVAILABLE,
            "enabled": effective_watcher_enabled(),
            "running": bool(self._observer is not None and self._enabled),
            "debounce_seconds": effective_watcher_debounce_seconds(),
            "watched_paths": list(self._watched_paths),
            "pending_count": len(self._pending),
            "in_flight_count": sum(1 for t in self._running.values() if not t.done()),
        }

    def recent_events(self, limit: int = 200) -> list[dict[str, Any]]:
        with self._events_lock:
            snapshot = list(self._events)
        snapshot.sort(key=lambda e: e.timestamp, reverse=True)
        return [e.as_dict() for e in snapshot[: max(1, min(limit, _EVENT_BUFFER_SIZE))]]

    # ----- internal: observer wiring -------------------------------------

    def _build_observer(self) -> None:
        """Construct a fresh Observer + handlers for every enabled library."""
        if not _WATCHDOG_AVAILABLE:
            return
        watched: list[str] = []
        observer = Observer()
        try:
            rows = db.list_libraries()
        except Exception as e:
            logger.warning("Watcher could not list libraries: {}", e)
            rows = []
        for row in rows:
            try:
                if not int(row["enabled"] or 0):
                    continue
                name = row["name"]
            except (KeyError, IndexError, TypeError):
                continue
            lib_path = MEDIA_ROOT / name
            if not lib_path.is_dir():
                logger.info("Watcher skipping {!r}: not a directory", name)
                continue
            try:
                handler = _LibraryEventHandler(
                    watcher=self, library=name, library_root=lib_path,
                )
                observer.schedule(handler, str(lib_path), recursive=True)
                watched.append(str(lib_path))
                logger.info("Watcher scheduled on {} -> {}", name, lib_path)
            except Exception as e:
                logger.warning("Watcher failed to schedule {}: {}", lib_path, e)
        if not watched:
            logger.info("Watcher has no library paths to watch")
        try:
            observer.start()
        except Exception as e:
            logger.warning("Watcher observer failed to start: {}", e)
            try:
                observer.stop()
            except Exception:
                pass
            return
        self._observer = observer
        self._watched_paths = watched

    def _teardown_observer(self) -> None:
        # Cancel pending debounce timers.
        for state in list(self._pending.values()):
            if state.timer is not None:
                try:
                    state.timer.cancel()
                except Exception:
                    pass
        self._pending.clear()
        if self._observer is not None:
            try:
                self._observer.stop()
                self._observer.join(timeout=5)
            except Exception as e:
                logger.warning("Watcher observer failed to stop cleanly: {}", e)
            self._observer = None
        self._watched_paths = []

    # ----- internal: event flow ------------------------------------------

    def _notify_event(self, library: str, show_folder: Path, raw_path: str,
                      is_dir: bool) -> None:
        """Called from watchdog's thread; hop onto the event loop."""
        loop = self._loop
        if loop is None or loop.is_closed():
            return
        try:
            loop.call_soon_threadsafe(
                self._schedule_debounce, library, show_folder, raw_path, is_dir,
            )
        except RuntimeError:
            # Loop is shutting down; drop the event.
            pass

    def _schedule_debounce(self, library: str, show_folder: Path,
                            raw_path: str, is_dir: bool) -> None:
        """Reset (or start) the debounce timer for ``show_folder``."""
        if self._loop is None:
            return
        debounce = effective_watcher_debounce_seconds()
        existing = self._pending.get(show_folder)
        if existing is None:
            self._record_event(
                event_type="detected",
                folder_path=str(show_folder),
                library=library,
                message=(
                    f"{'Folder' if is_dir else 'File'} change detected "
                    f"({Path(raw_path).name}); waiting {debounce}s for stability"
                ),
                status="info",
            )
            state = _PendingFolder(library=library)
            self._pending[show_folder] = state
        else:
            state = existing
            state.library = library
            state.last_event_at = time.monotonic()
            if state.timer is not None:
                try:
                    state.timer.cancel()
                except Exception:
                    pass
        state.timer = self._loop.call_later(
            debounce, self._fire_debounce, show_folder,
        )

    def _fire_debounce(self, show_folder: Path) -> None:
        state = self._pending.pop(show_folder, None)
        if state is None:
            return
        # If a previous run for the same folder is still in flight, just
        # drop this event — that run will pick up whatever's on disk now.
        in_flight = self._running.get(show_folder)
        if in_flight is not None and not in_flight.done():
            self._record_event(
                event_type="debounced",
                folder_path=str(show_folder),
                library=state.library,
                message="A previous run is still in flight; skipping duplicate trigger",
                status="info",
            )
            return
        task = asyncio.create_task(
            self._process_folder(show_folder, state.library),
            name=f"watcher-{show_folder.name}",
        )
        self._running[show_folder] = task

        def _cleanup(t: asyncio.Task) -> None:
            try:
                self._running.pop(show_folder, None)
            except Exception:
                pass

        task.add_done_callback(_cleanup)

    async def _process_folder(self, folder: Path, library: str) -> None:
        """Drive the scan → match → build pipeline for a settled folder."""
        try:
            if not folder.exists():
                self._record_event(
                    event_type="error",
                    folder_path=str(folder),
                    library=library,
                    message="Folder no longer exists; skipping",
                    status="warning",
                )
                return
            # Stability poll — make sure files aren't still being written.
            stable = await self._is_stable(folder)
            if not stable:
                # Reschedule for one more debounce cycle.
                self._record_event(
                    event_type="debounced",
                    folder_path=str(folder),
                    library=library,
                    message="Folder still changing; re-arming debounce",
                    status="info",
                )
                self._loop and self._loop.call_soon(
                    self._schedule_debounce, library, folder, str(folder), True,
                )
                return

            self._record_event(
                event_type="processing",
                folder_path=str(folder),
                library=library,
                message="Folder settled; running scan + match",
                status="info",
            )

            # 1. Refresh DB state for the whole library (cheap; idempotent).
            try:
                await asyncio.to_thread(scanner_svc.scan_library, library)
            except Exception as e:
                logger.warning("watcher scan_library({}) failed: {}", library, e)

            # 2. Determine the folder's kind.
            kind = _detect_kind(folder, library)

            # 3. If already matched, skip directly to build.
            binding = db.get_binding(str(folder))
            if binding and binding["external_id"]:
                self._record_event(
                    event_type="matched",
                    folder_path=str(folder),
                    library=library,
                    message=(
                        f"Already bound to {binding['provider']}:{binding['external_id']}; "
                        f"queuing build"
                    ),
                    status="info",
                )
                await self._queue_build(folder, kind, library)
                # Clear any prior review-queue entry — it auto-resolved.
                db.delete_watcher_review(str(folder))
                return

            # 4. Auto-match.
            settings = get_user_settings()
            lang = settings.preferred_language
            source = effective_metadata_source(library)
            try:
                if source == "tmdb":
                    if kind == "series":
                        data = await matcher_svc.auto_match_series_tmdb(
                            folder, language=lang,
                            threshold=settings.auto_match_threshold,
                        )
                    else:
                        data = await matcher_svc.auto_match_movie_tmdb(
                            folder, language=lang,
                            threshold=settings.auto_match_threshold,
                        )
                else:
                    if kind == "series":
                        data = await matcher_svc.auto_match_series(
                            folder, language=lang,
                            threshold=settings.auto_match_threshold,
                        )
                    else:
                        data = await matcher_svc.auto_match_movie(
                            folder, language=lang,
                            threshold=settings.auto_match_threshold,
                        )
            except Exception as e:
                logger.warning("watcher auto-match {} failed: {}", folder, e)
                db.upsert_watcher_review(
                    str(folder), library=library, kind=kind,
                    reason="error", detail=str(e),
                )
                self._record_event(
                    event_type="queued_for_review",
                    folder_path=str(folder),
                    library=library,
                    message=f"Auto-match raised: {e}",
                    status="warning",
                )
                return

            if not data:
                db.upsert_watcher_review(
                    str(folder), library=library, kind=kind,
                    reason="no_match",
                    detail="No candidate scored above the auto-match threshold.",
                )
                self._record_event(
                    event_type="queued_for_review",
                    folder_path=str(folder),
                    library=library,
                    message="No confident match; queued for manual review",
                    status="warning",
                )
                return

            # 5. Persist + build.
            try:
                if kind == "series":
                    scanner_svc.scan_series_folder(folder, library=library)
                else:
                    scanner_svc.scan_movie_folder(folder, library=library)
                sidecar_svc.write_sidecar(folder)
            except Exception as e:
                logger.warning("watcher post-match rescan {} failed: {}", folder, e)

            self._record_event(
                event_type="matched",
                folder_path=str(folder),
                library=library,
                message=f"Matched to {data.get('name') or data.get('title') or '?'}",
                status="success",
            )
            db.delete_watcher_review(str(folder))
            await self._queue_build(folder, kind, library)
        except Exception as e:
            logger.exception("watcher pipeline crashed on {}: {}", folder, e)
            self._record_event(
                event_type="error",
                folder_path=str(folder),
                library=library,
                message=f"Pipeline error: {e}",
                status="error",
            )

    async def _queue_build(self, folder: Path, kind: str, library: str) -> None:
        try:
            jid = build_svc.start_build(folder, kind, force=False)
            self._record_event(
                event_type="built",
                folder_path=str(folder),
                library=library,
                message=f"Build queued (job {jid})",
                status="success",
            )
        except Exception as e:
            logger.warning("watcher start_build {} failed: {}", folder, e)
            self._record_event(
                event_type="error",
                folder_path=str(folder),
                library=library,
                message=f"Build queue failed: {e}",
                status="error",
            )

    async def _is_stable(self, folder: Path) -> bool:
        """Return True once two consecutive size+mtime snapshots agree."""
        prev: Optional[tuple[int, float]] = None
        for _ in range(_STABILITY_POLL_MAX):
            try:
                snap = await asyncio.to_thread(_snapshot_folder, folder)
            except Exception as e:
                logger.warning("watcher stability snapshot failed: {}", e)
                return True  # Don't block the pipeline on stat errors.
            if prev is not None and snap == prev:
                return True
            prev = snap
            await asyncio.sleep(_STABILITY_POLL_INTERVAL)
        return prev is not None  # If we got at least one snapshot, proceed.

    # ----- internal: event buffer ----------------------------------------

    def _record_event(self, *, event_type: str, folder_path: str,
                       library: Optional[str], message: str,
                       status: str = "info") -> None:
        evt = WatcherEvent(
            timestamp=int(time.time()),
            event_type=event_type,
            folder_path=folder_path,
            library=library,
            message=message,
            status=status,
        )
        with self._events_lock:
            self._events.append(evt)
        logger.info("[watcher] {} {} :: {}", event_type, folder_path or "-", message)


def _snapshot_folder(folder: Path) -> tuple[int, float]:
    """Return (total_size, max_mtime) for every file under ``folder``.

    Skips errors silently so a transient EACCES on one file doesn't make the
    whole snapshot useless. Used by the stability poll.
    """
    total = 0
    max_mtime = 0.0
    for root, dirs, files in os.walk(folder, followlinks=False):
        # Drop hidden dirs in-place so os.walk doesn't recurse into them.
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for name in files:
            if name.startswith(".") or name.endswith(tuple(_IGNORED_SUFFIXES)):
                continue
            try:
                st = os.stat(os.path.join(root, name))
            except OSError:
                continue
            total += st.st_size
            if st.st_mtime > max_mtime:
                max_mtime = st.st_mtime
    return total, max_mtime


def _detect_kind(folder: Path, library: str) -> str:
    """Choose 'series' or 'movie' for a folder, mirroring the scheduler."""
    try:
        from .parser import detect_season_dirs, folder_looks_like_movie
    except Exception:
        return "series"
    try:
        if detect_season_dirs(folder):
            return "series"
        if folder_looks_like_movie(folder):
            return "movie"
    except Exception:
        pass
    # Fall back to the library's declared kind.
    try:
        row = db.get_library(library)
        if row is not None:
            lk = (row["kind"] or "tv").lower()
            return "movie" if lk == "movies" else "series"
    except Exception:
        pass
    return "series"


# Module-level singleton so other modules can share state.
watcher = Watcher()
